### Create category
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
    "name": "Bánh kem ít ngọt 2",
    "description": "Bánh kem ít ngọt, phù hợp với người ăn kiêng",
    "created_by": "NguyenND",
    "updated_by": "NguyenND"
}

### Update category
PUT http://localhost:8080/api/v1/categories/4
Content-Type: application/json

{
    "name": "Bánh kem trái cây",
    "description": "Bánh kem với các loại trái cây tươi ngon it ngot"
}


### Get category by id
GET http://localhost:8080/api/v1/categories/10


### Delete category by id
DELETE http://localhost:8080/api/v1/categories/9


### Create size
POST http://localhost:8080/api/v1/sizes
Content-Type: application/json

{
    "name": "Size S",
    "category_id": 10,
    "created_by": "NguyenND",
    "updated_by": "NguyenND"
}


### Update size
PUT http://localhost:8080/api/v1/sizes/6
Content-Type: application/json

{
    "name": "Size L",
    "category_id": 3,
    "created_by": "NguyenND",
    "updated_by": "NguyenND"
}

### Get size by id
GET http://localhost:8080/api/v1/sizes/5


### Delete size by id
DELETE http://localhost:8080/api/v1/sizes/5