database:
  host: localhost
  port: 5432
  username: bakery
  password: nguyen
  dbname: bakery
  sslmode: disable
  timezone: Asia/Ho_Chi_Minh
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_lifetime: 5 # in minutes

jwt:
  secret: your_jwt_secret_key
  algorithm: HS256
  expiration: 3600